# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/enjoy301"

[social.params]
icon = "brand-github"

[[social]]
identifier = "hemail"
name = "HEmail"
url = "mailto:eunjong147@pusan.ac.kr"

[social.params]
icon = "messages"
